const Razorpay = require('razorpay');
const crypto = require('crypto');
const logger = require('../utils/logger');

class PaymentService {
    constructor() {
        if (!process.env.RAZORPAY_KEY_ID || !process.env.RAZORPAY_KEY_SECRET) {
            logger.warn('Razorpay credentials missing. Payment services will fail.');
        } else {
            this.razorpay = new Razorpay({
                key_id: process.env.RAZORPAY_KEY_ID,
                key_secret: process.env.RAZORPAY_KEY_SECRET,
            });
        }
    }

    /**
     * Initializes a payment intent/order on the gateway.
     * @param {number} amountInRupees - The total transaction amount in INR.
     * @param {string} receiptId - Your internal database order ID mapping.
     * @returns {Promise<Object>} - The gateway order payload required by the frontend.
     */
    async createOrder(amountInRupees, receiptId) {
        try {
            const options = {
                amount: amountInRupees * 100, // Razorpay processes amounts in the smallest currency sub-unit (paise)
                currency: 'INR',
                receipt: receiptId.toString(),
                payment_capture: 1 // Auto-capture payment upon authorization
            };

            const order = await this.razorpay.orders.create(options);
            return order;
        } catch (error) {
            logger.error(`Payment Gateway Order Creation Failed: ${error.message}`);
            throw new Error('Failed to initialize payment gateway.');
        }
    }

    /**
     * Cryptographically verifies the webhook or frontend callback payload to prevent spoofing.
     * @param {string} razorpayOrderId - The order ID generated by Razorpay.
     * @param {string} razorpayPaymentId - The transaction ID generated by Razorpay.
     * @param {string} signature - The HMAC hex signature returned by the client.
     * @returns {boolean} - True if the payment is authentic.
     */
    verifyPaymentSignature(razorpayOrderId, razorpayPaymentId, signature) {
        try {
            const generatedSignature = crypto
                .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
                .update(`${razorpayOrderId}|${razorpayPaymentId}`)
                .digest('hex');

            return generatedSignature === signature;
        } catch (error) {
            logger.error(`Signature Verification Error: ${error.message}`);
            return false;
        }
    }
}

module.exports = new PaymentService();